grails-app/domain/com/mbwanajm/darproperty/MonthlyIssue.groovy
package com.mbwanajm.darproperty

/**
 * Contains information about dar property monthly issues
 * Created with IntelliJ IDEA.
 * User: mbwana
 * Date: 5/3/12
 * Time: 8:10 PM
 * To change this template use File | Settings | File Templates.
 */
class MonthlyIssue {
    String title;
    String embedCode;
    byte[] image;

    static constraints = {
        title(nullable: false)
        embedCode(nullable: false, maxSize: 1000)
        image(nullable: true, minSize: 1, maxSize: 10485760)  // 10MB
    }
}

grails-app/controllers/com/mbwanajm/darproperty/MonthlyIssueController.groovy
package com.mbwanajm.darproperty

import org.springframework.dao.DataIntegrityViolationException

class MonthlyIssueController {
    def scaffold = true;

    def showAllMagazines() {
        def magazines = MonthlyIssue.listOrderById(order: 'desc');
        [magazines: magazines]
    }

    def viewMagazine() {
        def magazine = MonthlyIssue.get(params.id)
        [magazine: magazine]
    }

    def viewLatestMagazine() {
        def magazine = MonthlyIssue.listOrderById(order: 'desc', max:1)[0];
        render(view: "viewMagazine", model: [magazine: magazine])
    }

}

grails-app/views/monthlyIssue/_form.gsp
<%@ page import="com.mbwanajm.darproperty.MonthlyIssue" %>



<div class="fieldcontain ${hasErrors(bean: monthlyIssueInstance, field: 'title', 'error')} ">
    <label for="title">
        <g:message code="monthlyIssue.title.label" default="Title"/>

    </label>
    <g:textField name="title" value="${monthlyIssueInstance?.title}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: monthlyIssueInstance, field: 'embedCode', 'error')} ">
    <label for="embedCode">
        <g:message code="monthlyIssue.embedCode.label" default="Embed Code"/>

    </label>
    <g:textArea name="embedCode" cols="40" rows="5" maxlength="1000" value="${monthlyIssueInstance?.embedCode}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: monthlyIssueInstance, field: 'image', 'error')} ">
    <label for="image">
        <g:message code="monthlyIssue.image.label" default="Image"/>

    </label>
    <input type="file" id="image" name="image"/>
</div>


grails-app/views/monthlyIssue/create.gsp
<%@ page import="com.mbwanajm.darproperty.MonthlyIssue" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'monthlyIssue.label', default: 'MonthlyIssue')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-monthlyIssue" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                     default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-monthlyIssue" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${monthlyIssueInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${monthlyIssueInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form action="save" enctype="multipart/form-data">
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save"
                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/monthlyIssue/edit.gsp
<%@ page import="com.mbwanajm.darproperty.MonthlyIssue" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'monthlyIssue.label', default: 'MonthlyIssue')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-monthlyIssue" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                   default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-monthlyIssue" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${monthlyIssueInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${monthlyIssueInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form method="post" enctype="multipart/form-data">
        <g:hiddenField name="id" value="${monthlyIssueInstance?.id}"/>
        <g:hiddenField name="version" value="${monthlyIssueInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate=""
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/monthlyIssue/list.gsp
<%@ page import="com.mbwanajm.darproperty.MonthlyIssue" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'monthlyIssue.label', default: 'MonthlyIssue')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-monthlyIssue" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                   default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-monthlyIssue" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="title" title="${message(code: 'monthlyIssue.title.label', default: 'Title')}"/>

            <g:sortableColumn property="embedCode"
                              title="${message(code: 'monthlyIssue.embedCode.label', default: 'Embed Code')}"/>


        </tr>
        </thead>
        <tbody>
        <g:each in="${monthlyIssueInstanceList}" status="i" var="monthlyIssueInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show"
                            id="${monthlyIssueInstance.id}">${fieldValue(bean: monthlyIssueInstance, field: "title")}</g:link></td>

                <td>${fieldValue(bean: monthlyIssueInstance, field: "embedCode")}</td>

            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${monthlyIssueInstanceTotal}"/>
    </div>
</div>
</body>
</html>

grails-app/views/monthlyIssue/show.gsp
<%@ page import="com.mbwanajm.darproperty.MonthlyIssue" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'monthlyIssue.label', default: 'MonthlyIssue')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-monthlyIssue" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                   default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-monthlyIssue" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list monthlyIssue">

        <g:if test="${monthlyIssueInstance?.title}">
            <li class="fieldcontain">
                <span id="title-label" class="property-label"><g:message code="monthlyIssue.title.label"
                                                                         default="Title"/></span>

                <span class="property-value" aria-labelledby="title-label"><g:fieldValue bean="${monthlyIssueInstance}"
                                                                                         field="title"/></span>

            </li>
        </g:if>

        <g:if test="${monthlyIssueInstance?.embedCode}">
            <li class="fieldcontain">
                <span id="embedCode-label" class="property-label"><g:message code="monthlyIssue.embedCode.label"
                                                                             default="Embed Code"/></span>

                <span class="property-value" aria-labelledby="embedCode-label"><g:fieldValue
                        bean="${monthlyIssueInstance}" field="embedCode"/></span>

            </li>
        </g:if>

        <g:if test="${monthlyIssueInstance?.image}">
            <li class="fieldcontain">
                <span id="image-label" class="property-label"><g:message code="monthlyIssue.image.label"
                                                                         default="Image"/></span>

            </li>
        </g:if>

    </ol>
    <g:form>
        <fieldset class="buttons">
            <g:hiddenField name="id" value="${monthlyIssueInstance?.id}"/>
            <g:link class="edit" action="edit" id="${monthlyIssueInstance?.id}"><g:message
                    code="default.button.edit.label" default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/monthlyIssue/showAllMagazines.gsp
<html>
<head>
    <title>DarProperty>>The Magazine</title>
    <meta name="layout" content="main"/>
</head>

<body>
<div class="container">
    <g:render template="../pageTitle" model="[title: 'All Our Magazines']"></g:render>
    <br>

    <div class='row'>

        <g:each in="${magazines}" var="magazine">
            <div class="col-lg-3">
                <br>
                <b class="wid-view-more ">${magazine.title}</b>
                <hr class="style-one">
                <br>
                <g:link controller='monthlyIssue' action='viewMagazine' id='${magazine.id}'>
                    <img src="<g:createLink controller='image' action='renderMonthlyIssuePhoto'
                                            id='${magazine.id}'/>" alt="read this"/>
                </g:link>

                <br>

                <div >
                    <p class="pull-left">

                        <small class="hd2">  <g:message code="home.share"></g:message> <i class="fa fa-share"></i> </small>

                        <span class="" style="color:#4a6ea9; font-size:30pt;">
                            <!-- FACEBOOK -->
                            <a href="http://www.facebook.com/dialog/feed?app_id=1670558763159469&redirect_uri=http%3A%2F%2Fwww.darproperty.co.tz%2FmonthlyIssue%2FviewMagazine%2F${magazine.id}&link=http%3A%2F%2Fwww.darproperty.co.tz%2FmonthlyIssue%2FviewMagazine%2F${magazine.id}"
                               target="">
                                <span class="fa fa-facebook-square hidden-sm hidden-xs"></span>
                                <span class="fa fa-facebook hidden-lg"></span>
                                %{-- <img
                                         src="${resource(dir: 'bootstrap/imgs/', file: 'facebook.png')}"
                                         alt="Facebook"
                                         class=""
                                         title="Share on Facebook" />--}%
                            </a>
                        </span>

                        <span class=" hidden-xs hidden-sm"
                              style="background-color:#EEE; border-color:transparent; border-width: 0px;">
                        </span>

                        <span class=" hidden-lg" style="color:#2ab200;font-size:30pt;">
                            <!-- WHATSAPP -->
                            <a
                                    href="whatsapp://send?text= Check  ${magazine.title}  at  Darproperty  READ ONLINE NOW:-> http://www.darproperty.co.tz/monthlyIssue/viewMagazine/${magazine.id}"
                                    data-action="share/whatsapp/share"
                                    target="_blank"
                                    title="Whatsapp share">
                                <img
                                        src="${resource(dir: 'bootstrap/imgs/', file: 'whatsappgreen.png')}"
                                        alt="Whatsapp"
                                        width="40"
                                        title="Share on Whatsapp"/>
                            </a>
                        </span>

                        <span style="color:#659fcb; font-size:30pt;" class="text-info" >
                            <!-- TWITTER -->

                            <!--class="twitter-share-button"{count}  -->
                            <a href="https://twitter.com/intent/tweet?text=Read%20now%20online%20${magazine.title}%20issue%20at%20DarProperty%20,%20VIA%20@thedarproperty%20in&amp;url=http%3A%2F%2Fwww.darproperty.co.tz%2FmonthlyIssue%2FviewMagazine%2F${magazine.id}"
                               class="shortenUrl"
                               data-social-url="https://twitter.com/intent/tweet?text=Read+now+${magazine.title}+issue+VIA+@thedarproperty+in&amp;url="
                               data-target-url="http://www.darproperty.co.tz/monthlyIssue/viewMagazine/${magazine.id}"
                               target="_blank">
                                <span class="fa fa-twitter-square hidden-sm hidden-xs"></span>
                                <span class="fa fa-twitter hidden-lg"></span>
                                %{--<img
                                        src="${resource(dir: 'bootstrap/imgs/', file: 'twitter.png')}"
                                        alt="Twitter"
                                        class=""
                                        title="Share on Twitter"/>--}%
                            </a>
                        </span>
                    </p>
                    <div class="hidden-md hidden-lg">
                        <br><br><br><br>
                    </div>
                </div>
            </div>
        </g:each>


    </div>
</div>

</body>
</html>

grails-app/views/monthlyIssue/viewMagazine.gsp
<html>
<head>
    <title>The Magazine(${magazine.title})</title>
    <meta name="layout" content="main"/>
</head>

<body>

<% def title = "Reading $magazine.title issue" %>
<g:render template="../pageTitle" model="[title: title]"></g:render>
<div class="row">
    <div class="span12" align="center">
        ${magazine.embedCode}
    </div>
</div>
<script>
    $(document).ready(function () {
        function issuu() {
            var issue = $(".issuuembed");
            var style =
                    "width: " + issue.parent().innerWidth() +
                    "px; height: "  + issue.parent().innerWidth() * .7625 + "px;";

            issue.attr({"style": style });
        }

        $(function () {
            issuu();
            $(window).resize(function (e) {
                issuu();
            });
        });
    });
</script>
</body>

</html>